import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case chinese = "zh-Hans"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english: return "English"
        case .chinese: return "中文"
        }
    }
}

func L(_ key: String) -> String {
    guard UserDefaults.standard.string(forKey: "general.language") == AppLanguage.chinese.rawValue else { return key }
    return zhHansStrings[key] ?? key
}

func L(_ key: String, _ arguments: CVarArg...) -> String {
    String(format: L(key), arguments: arguments)
}

private let zhHansStrings: [String: String] = [
    "General": "通用",
    "Modules": "模块",
    "Appearance": "外观",
    "Extensions": "扩展",
    "Advanced": "高级",
    "Quit": "退出",
    "Startup": "启动",
    "Launch at login": "登录时启动",
    "Show menu bar icon": "显示菜单栏图标",
    "Show in screen recordings": "在屏幕录制中显示",
    "Language": "语言",
    "Display language": "显示语言",
    "Display": "显示",
    "Show on all Spaces": "在所有空间中显示",
    "Hide side slots": "隐藏两侧占位区",
    "Hide on fullscreen": "全屏时隐藏",
    "Animation Speed": "动画速度",
    "Normal": "正常",
    "Reduced": "降低",
    "Minimal": "最小",
    "Behavior": "行为",
    "Expanded collapse delay": "展开收起延迟",
    "How long expanded content stays visible": "展开内容保持可见的时长",
    "Hover expand delay": "悬停展开延迟",
    "How long to hover the notch before it peeks open": "悬停刘海多久后预览展开",
    "Interaction": "交互",
    "Island surface swipes": "岛面滑动手势",
    "Notch haptic intensity": "刘海触觉反馈强度",
    "Feedback strength when entering the notch": "进入刘海区域时的反馈强度",
    "Allow Command+Q to quit": "允许 Command+Q 退出",
    "Turn this off to prevent accidental quits while interacting with the notch.": "关闭后可避免与刘海交互时误触退出。",
    "Permissions": "权限",
    "Accessibility": "辅助功能",
    "Gesture detection and system events": "手势检测和系统事件",
    "Calendar": "日历",
    "Show upcoming events in the island": "在岛中显示即将到来的日程",
    "Location": "定位",
    "Weather information for your location": "获取当前位置的天气信息",
    "Bluetooth": "蓝牙",
    "Connected device notifications": "已连接设备通知",
    "Granted": "已授权",
    "Grant Access": "授予权限",
    "Mascot": "吉祥物",
    "Show mascot in Pomodoro": "在番茄钟中显示吉祥物",
    "Temperature Unit": "温度单位",
    "Script": "脚本",
    "Edit Script…": "编辑脚本…",
    "Show island on": "岛显示在",
    "Pick a specific display or let SuperIsland choose": "选择指定显示器，或让 SuperIsland 自动选择",
    "Automatic": "自动",
    "Reset All Settings": "重置所有设置",
    "Restore all settings to their defaults": "将所有设置恢复为默认值",
    "Reset": "重置",
    "Cancel": "取消",
    "This will reset all SuperIsland settings to their defaults.": "这会将所有 SuperIsland 设置恢复为默认值。",
    "Version": "版本",
    "Build": "构建",
    "Updates": "更新",
    "Checking...": "正在检查…",
    "You're up to date": "已是最新版本",
    "Version %@ available": "发现版本 %@",
    "Update": "更新",
    "Check for Updates": "检查更新",
    "Bounce": "弹性",
    "Spring bounce for compact ↔ expanded transitions": "紧凑与展开切换时的弹簧弹性",
    "Filter": "筛选",
    "%d shown": "显示 %d 个",
    "Select an extension": "选择一个扩展",
    "Choose an extension from the left panel.": "请从左侧面板选择一个扩展。",
    "Deactivate": "停用",
    "Activate": "启用",
    "Disconnect": "断开连接",
    "Log Out": "退出登录",
    "Start Login": "开始登录",
    "Refresh QR": "刷新二维码",
    "Connected. New messages will be synced from this login.": "已连接。新消息会从此登录同步。",
    "Scan this QR with WhatsApp on your phone": "请用手机 WhatsApp 扫描此二维码",
    "Preparing secure login session...": "正在准备安全登录会话…",
    "WhatsApp Web Login": "WhatsApp Web 登录",
    "Linear Login": "Linear 登录",
    "Last.fm Login": "Last.fm 登录",
    "Details": "详情",
    "Author": "作者",
    "Refresh": "刷新",
    "Triggers": "触发方式",
    "Recent Logs": "最近日志",
    "Settings": "设置",
    "Battery": "电池",
    "Notifications": "通知",
    "All": "全部",
    "Active": "已启用",
    "Inactive": "未启用",
    "Reload": "重新加载",
    "Installed": "已安装",
    "Bundled": "内置",
    "Debug": "调试",
    "About": "关于",
    "Reset Settings": "重置设置",
    "Expired": "已过期",
    "Logged in": "已登录",
    "Not logged in": "未登录",
    "Your Linear session has expired. Authenticate again to resume mention syncing.": "Linear 会话已过期。请重新授权以继续同步提及。",
    "Linear is authenticated. New mentions will appear in the Super Island.": "Linear 已授权。新的提及会显示在 SuperIsland 中。",
    "Authenticate with Linear to start mention notifications and inline replies.": "授权 Linear 后即可接收提及通知并进行行内回复。",
    "Log In Again": "重新登录",
    "Reconnect": "重新连接",
    "Log In to Linear": "登录 Linear",
    "Your Last.fm session has expired. Authenticate again to resume scrobbling.": "Last.fm 会话已过期。请重新授权以继续记录播放。",
    "Last.fm is connected. New plays will scrobble automatically.": "Last.fm 已连接。新的播放会自动记录。",
    "Last.fm is connected as %@. New plays will scrobble automatically.": "Last.fm 已连接为 %@。新的播放会自动记录。",
    "Authenticate with Last.fm to start scrobbling your listening history.": "授权 Last.fm 后即可开始记录你的收听历史。",
    "Log In to Last.fm": "登录 Last.fm",
    "Scope: %@": "范围：%@",
    "Account: %@": "账号：%@",
    "Expired at %@": "已于 %@ 过期",
    "Expires at %@": "过期时间：%@",
    "Idle": "空闲",
    "Loading": "加载中",
    "QR Ready": "二维码已就绪",
    "Connected": "已连接",
    "Error": "错误",
    "Animation": "动画",
    "Compact Island Size": "紧凑岛尺寸",
    "Width": "宽度",
    "Height": "高度",
    "Pill width on notched Macs": "刘海 Mac 上胶囊区域的宽度",
    "Pill height on notched Macs": "刘海 Mac 上胶囊区域的高度",
    "No events": "没有日程",
    "Join": "加入",
    "No more events today": "今天没有更多日程",
    "Today": "今天",
    "Upcoming": "即将到来",
    "Nothing this week": "本周没有日程",
    "All Day": "全天",
    "Edit": "编辑",
    "Add script": "添加脚本",
    "Clear": "清空",
    "Done (⌘↩)": "完成 (⌘↩)",
    "Text scrolls upward in the island as you speak.": "朗读时文本会在岛中向上滚动。",
    "System Volume": "系统音量",
    "Media Apps": "媒体应用",
    "No supported media apps are currently playing.": "当前没有支持的媒体应用正在播放。",
    "Focus Off": "专注已关闭",
    "Battery Trend": "电池趋势",
    "Need more samples": "需要更多样本",
    "Shelf": "托盘",
    "Drop onto the island": "拖放到岛上",
    "Items stay pinned here until you remove them.": "项目会固定在这里，直到你移除它们。",
    "AirDrop": "隔空投送",
    "Drop to share": "拖放以分享",
    "Drop files here": "将文件拖到这里",
    "Tray": "托盘",
    "Open": "打开",
    "Show in Finder": "在访达中显示",
    "Share via AirDrop": "通过隔空投送分享",
    "Remove": "移除",
    "No notifications": "没有通知",
    "No Notifications": "没有通知",
    "Notifications from apps will appear here": "来自应用的通知会显示在这里",
    "%d notification": "%d 条通知",
    "%d notifications": "%d 条通知",
    "Clear All": "全部清除",
    "Off": "关闭",
    "Subtle": "轻微",
    "Medium": "中等",
    "Strong": "强",
    "Now Playing": "正在播放",
    "Volume": "音量",
    "Connectivity": "连接",
    "Weather": "天气",
    "Teleprompter": "提词器",
    "Home": "首页",
    "None": "无",
    "Media Player": "媒体播放器",
    "SuperIsland Settings": "SuperIsland 设置",
    "Update Available": "发现新版本",
    "Version %@ is ready to install.": "版本 %@ 已准备好安装。",
    "Downloading %d%%": "正在下载 %d%%",
    "Installing...": "正在安装…",
    "Later": "稍后",
    "Open Release Page": "打开发布页面",
    "No emoji found": "未找到表情",
    "Keep typing to refine the search": "继续输入以缩小搜索范围",
    "Welcome to SuperIsland": "欢迎使用 SuperIsland",
    "Your notch, reimagined. A quick setup\nand you're ready to go.": "重新想象你的刘海区域。快速设置后\n即可开始使用。",
    "Get Started": "开始使用",
    "SuperIsland needs a few permissions to work properly.": "SuperIsland 需要一些权限才能正常工作。",
    "Required": "必需",
    "Continue": "继续",
    "Swipe the island": "滑动岛",
    "Swipe left or right on the notch to switch between modules.": "在刘海区域左右滑动即可切换模块。",
    "SWIPE": "滑动",
    "Add extra capabilities to your island.": "为你的岛添加额外能力。",
    "Understood": "明白了",
    "You're all set": "设置完成",
    "SuperIsland will run in the background.": "SuperIsland 会在后台运行。",
    "Open Settings Instead": "改为打开设置",
    "Back": "返回",
    "Open Settings": "打开设置",
    "Request Access": "请求权限",
    "SuperIsland Setup": "SuperIsland 设置向导",
    "Unsupported setting field: %@": "不支持的设置字段：%@",
    "Screen Recording": "屏幕录制",
    "Microphone": "麦克风",
    "Needed for gesture detection and system event monitoring": "用于手势检测和系统事件监听",
    "Lets SuperIsland appear properly in screen recordings": "让 SuperIsland 能在屏幕录制中正确显示",
    "Show upcoming events in the Super Island": "在 SuperIsland 中显示即将到来的日程",
    "Mirror notifications in the Super Island": "在 SuperIsland 中镜像通知",
    "Audio visualization for the spectrogram": "用于频谱图的音频可视化",
    "Provide weather information for your location": "根据你的位置提供天气信息",
    "Couldn't build the mascot download URL.": "无法生成吉祥物下载地址。",
    "The mascot template response couldn't be read.": "无法读取吉祥物模板响应。",
    "The mascot service returned HTTP %d.": "吉祥物服务返回 HTTP %d。",
    "Could not find app in update package.": "更新包中未找到应用。",
    "Could not open update package.": "无法打开更新包。",
    "Tomorrow": "明天",
    "Yesterday": "昨天",
    "%d events": "%d 个日程",
    "+%d more": "+%d 个更多",
    "1 event": "1 个日程",
    "Not connected": "未连接",
    "Excellent signal": "信号极佳",
    "Strong signal": "信号强",
    "Fair signal": "信号一般",
    "Weak signal": "信号弱",
    "Do Not Disturb": "勿扰模式",
    "Unknown": "未知",
    "Low": "低",
    "Mod": "中",
    "High": "高",
    "Very High": "非常高",
    "Extreme": "极高",
    "Good": "良好",
    "Moderate": "中等",
    "Unhealthy*": "轻度污染",
    "Unhealthy": "不健康",
    "Very Poor": "很差",
    "Hazardous": "危险",
    "Partly Cloudy": "多云",
    "Foggy": "有雾",
    "Drizzle": "毛毛雨",
    "Rain": "雨",
    "Freezing Rain": "冻雨",
    "Snow": "雪",
    "Snow Grains": "雪粒",
    "Showers": "阵雨",
    "Snow Showers": "阵雪",
    "Thunderstorm": "雷暴",
    "Hailstorm": "冰雹",
    "Now": "现在",
    "File": "文件",
    "Folder": "文件夹",
    "Link": "链接",
    "System": "系统",
    "No events scheduled today": "今天没有日程",
    "Teleprompter Script": "提词器脚本",
    "Refreshing QR code...": "正在刷新二维码…",
    "Logging out...": "正在退出登录…",
    "WhatsApp provider unavailable": "WhatsApp 服务不可用",
    "Node.js required": "需要 Node.js",
    "Starting WhatsApp realtime bridge...": "正在启动 WhatsApp 实时桥接…",
    "Failed to start WhatsApp bridge": "启动 WhatsApp 桥接失败",
    "Node.js Required for WhatsApp": "WhatsApp 需要 Node.js",
    "The WhatsApp integration needs Node.js to run. It's a free, one-time install — just download the macOS installer from nodejs.org and restart Super Island.": "WhatsApp 集成需要 Node.js 才能运行。这是一次性免费安装；请从 nodejs.org 下载 macOS 安装器，然后重启 SuperIsland。",
    "WhatsApp provider error": "WhatsApp 服务错误",
    "Connecting to WhatsApp...": "正在连接 WhatsApp…",
    "Scan QR code with WhatsApp": "使用 WhatsApp 扫描二维码",
    "Agents Status port %d is in use": "Agents Status 端口 %d 已被占用",
    "Another process on this Mac is already listening on 127.0.0.1:%d. A leftover agents-status server from a previous Super Island run is the most common cause. Open Terminal and run `lsof -iTCP:%d -sTCP:LISTEN` to find it, then quit that process (or reboot) and relaunch Super Island.": "此 Mac 上已有其他进程正在监听 127.0.0.1:%d。最常见原因是上次 SuperIsland 运行后残留了 agents-status 服务。请打开终端运行 `lsof -iTCP:%d -sTCP:LISTEN` 找到该进程，然后退出它（或重启电脑）并重新启动 SuperIsland。",
    "Python 3 required for Agents Status": "Agents Status 需要 Python 3",
    "Agents Status tracks your Claude Code and Codex CLI sessions through a small background service that needs Python 3. On macOS, install the Command Line Tools by running `xcode-select --install` in Terminal, then restart Super Island.": "Agents Status 通过一个需要 Python 3 的小型后台服务跟踪 Claude Code 和 Codex CLI 会话。在 macOS 上，请在终端运行 `xcode-select --install` 安装命令行工具，然后重启 SuperIsland。",
    "Access Claude Code credentials for AI usage status.": "访问 Claude Code 凭据以显示 AI 使用状态。",
    "Grant": "授权",
    "Pomodoro Timer": "番茄钟",
    "Focus timer with countdown in the island": "在岛中显示倒计时的专注计时器",
    "WhatsApp Web": "WhatsApp Web",
    "Route WhatsApp messages to the island": "将 WhatsApp 消息转到岛中",
    "Requires Login": "需要登录",
    "AI Usage": "AI 使用量",
    "Claude & Codex usage rings in the notch": "在刘海中显示 Claude 与 Codex 使用量圆环",
    "Added": "已添加",
    "Add": "添加",
    "%d of 4 granted": "已授权 %d / 4",
    "Launching...": "正在启动…"
]
